### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by macMikey** [miyako/language-4dcatalog#4]
Installing “language-4dcatalog@0.11.1” failed.Hide output…
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/me/.atom/packages/language-4dcatalog/node_modules/npm/node_modules/query-string/index.d.ts'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:696:12)
    at WriteStream.emit (events.js:182:13)
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:211:14
    at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:169:20)

**Comment by miyako** [comment]
what atom version?

**Comment by macMikey** [comment]
1.47.0

**Comment by miyako** [comment]
On Mac, you can navigate in Finder to your user home directory, enter command+shift+``.`` to display hidden files. Do you not see the file "/Users/me/.atom/packages/language-4dcatalog/node_modules/npm/node_modules/query-string/index.d.ts" ?

<img width="844" alt="スクリーンショット 2020-06-02 3 07 51" src="https://user-images.githubusercontent.com/1725068/83439536-51986d80-a47e-11ea-87a9-4204fd408794.png">

**Comment by macMikey** [comment]
it looks like after changing the permissions for atom and giving it full disk, uninstalling and reinstalling all the package, the errors ceased.
